/* Cruzando Fronteras de Lenguaje — Banco de palabras (200)
   Formato: [español, inglés, emoji, ejemplo en inglés, ejemplo en español] */

const CATEGORIAS = [
  {
    id: "animales", nombre: "Animales", emoji: "🐶", color: "#38bdf8",
    palabras: [
      ["perro","dog","🐶","The dog is very big.","El perro es muy grande."],
      ["gato","cat","🐱","My cat sleeps a lot.","Mi gato duerme mucho."],
      ["pájaro","bird","🐦","The bird can fly.","El pájaro puede volar."],
      ["pez","fish","🐟","The fish lives in water.","El pez vive en el agua."],
      ["caballo","horse","🐴","The horse runs fast.","El caballo corre rápido."],
      ["vaca","cow","🐮","The cow gives us milk.","La vaca nos da leche."],
      ["cerdo","pig","🐷","The pig is pink.","El cerdo es rosado."],
      ["oveja","sheep","🐑","The sheep is white.","La oveja es blanca."],
      ["pollo","chicken","🐔","The chicken eats corn.","El pollo come maíz."],
      ["pato","duck","🦆","The duck swims in the lake.","El pato nada en el lago."],
      ["conejo","rabbit","🐰","The rabbit eats carrots.","El conejo come zanahorias."],
      ["ratón","mouse","🐭","The mouse is very small.","El ratón es muy pequeño."],
      ["león","lion","🦁","The lion is strong.","El león es fuerte."],
      ["tigre","tiger","🐯","The tiger has stripes.","El tigre tiene rayas."],
      ["oso","bear","🐻","The bear likes honey.","Al oso le gusta la miel."],
      ["mono","monkey","🐵","The monkey climbs the tree.","El mono sube al árbol."],
      ["elefante","elephant","🐘","The elephant is huge.","El elefante es enorme."],
      ["jirafa","giraffe","🦒","The giraffe has a long neck.","La jirafa tiene cuello largo."],
      ["serpiente","snake","🐍","The snake is green.","La serpiente es verde."],
      ["araña","spider","🕷️","The spider makes a web.","La araña hace una telaraña."],
      ["abeja","bee","🐝","The bee makes honey.","La abeja hace miel."],
      ["mariposa","butterfly","🦋","The butterfly is beautiful.","La mariposa es hermosa."],
      ["tortuga","turtle","🐢","The turtle walks slowly.","La tortuga camina lento."],
      ["rana","frog","🐸","The frog jumps high.","La rana salta alto."],
      ["lobo","wolf","🐺","The wolf lives in the forest.","El lobo vive en el bosque."]
    ]
  },
  {
    id: "familia", nombre: "Familia y personas", emoji: "👨‍👩‍👧", color: "#f472b6",
    palabras: [
      ["madre","mother","👩","My mother cooks dinner.","Mi madre cocina la cena."],
      ["padre","father","👨","My father works here.","Mi padre trabaja aquí."],
      ["hermana","sister","👧","My sister is ten.","Mi hermana tiene diez años."],
      ["hermano","brother","👦","My brother plays soccer.","Mi hermano juega fútbol."],
      ["abuela","grandmother","👵","My grandmother tells stories.","Mi abuela cuenta historias."],
      ["abuelo","grandfather","👴","My grandfather reads a book.","Mi abuelo lee un libro."],
      ["tía","aunt","💁‍♀️","My aunt lives in Lima.","Mi tía vive en Lima."],
      ["tío","uncle","💁‍♂️","My uncle has a car.","Mi tío tiene un carro."],
      ["primo","cousin","🧒","My cousin is my friend.","Mi primo es mi amigo."],
      ["bebé","baby","👶","The baby is sleeping.","El bebé está durmiendo."],
      ["hija","daughter","👧","She is my daughter.","Ella es mi hija."],
      ["hijo","son","👦","He is my son.","Él es mi hijo."],
      ["amigo","friend","🤝","My friend helps me.","Mi amigo me ayuda."],
      ["familia","family","👨‍👩‍👧","My family is big.","Mi familia es grande."],
      ["niña","girl","👧","The girl is happy.","La niña está feliz."],
      ["niño","boy","👦","The boy runs fast.","El niño corre rápido."],
      ["mujer","woman","👩","The woman is a doctor.","La mujer es doctora."],
      ["hombre","man","👨","The man is tall.","El hombre es alto."],
      ["vecino","neighbor","🏘️","My neighbor is kind.","Mi vecino es amable."],
      ["esposa","wife","👰","His wife is a teacher.","Su esposa es maestra."],
      ["esposo","husband","🤵","Her husband cooks well.","Su esposo cocina bien."],
      ["sobrina","niece","👧","My niece is five.","Mi sobrina tiene cinco años."],
      ["sobrino","nephew","👦","My nephew likes dogs.","A mi sobrino le gustan los perros."],
      ["persona","person","🧍","That person is my teacher.","Esa persona es mi maestra."],
      ["gente","people","👥","Many people are here.","Mucha gente está aquí."]
    ]
  },
  {
    id: "colegio", nombre: "El colegio", emoji: "🏫", color: "#a78bfa",
    palabras: [
      ["escuela","school","🏫","I go to school every day.","Voy a la escuela todos los días."],
      ["maestra","teacher","👩‍🏫","My teacher is very nice.","Mi maestra es muy amable."],
      ["alumno","student","🧑‍🎓","The student asks a question.","El alumno hace una pregunta."],
      ["libro","book","📖","This book is interesting.","Este libro es interesante."],
      ["cuaderno","notebook","📓","My notebook is blue.","Mi cuaderno es azul."],
      ["lápiz","pencil","✏️","I need a pencil.","Necesito un lápiz."],
      ["lapicero","pen","🖊️","The pen does not work.","El lapicero no funciona."],
      ["borrador","eraser","🧽","Can I use your eraser?","¿Puedo usar tu borrador?"],
      ["regla","ruler","📏","I draw with a ruler.","Dibujo con una regla."],
      ["mochila","backpack","🎒","My backpack is heavy.","Mi mochila está pesada."],
      ["tijeras","scissors","✂️","The scissors are on the table.","Las tijeras están en la mesa."],
      ["pegamento","glue","🧴","I need glue for my project.","Necesito pegamento para mi proyecto."],
      ["papel","paper","📄","Give me a sheet of paper.","Dame una hoja de papel."],
      ["pizarra","board","🪧","The teacher writes on the board.","La maestra escribe en la pizarra."],
      ["silla","chair","🪑","Please sit on the chair.","Por favor siéntate en la silla."],
      ["mesa","table","🗄️","The books are on the table.","Los libros están en la mesa."],
      ["tarea","homework","📝","I do my homework at night.","Hago mi tarea en la noche."],
      ["examen","test","📋","The test is on Monday.","El examen es el lunes."],
      ["clase","class","📚","My class starts at eight.","Mi clase empieza a las ocho."],
      ["pregunta","question","❓","I have a question.","Tengo una pregunta."],
      ["respuesta","answer","✅","Your answer is correct.","Tu respuesta es correcta."],
      ["palabra","word","🔤","This word is new for me.","Esta palabra es nueva para mí."],
      ["número","number","🔢","Write the number here.","Escribe el número aquí."],
      ["recreo","recess","⚽","We play at recess.","Jugamos en el recreo."],
      ["patio","playground","🛝","The playground is big.","El patio es grande."]
    ]
  },
  {
    id: "comida", nombre: "La comida", emoji: "🍎", color: "#fb923c",
    palabras: [
      ["agua","water","💧","I drink water every day.","Tomo agua todos los días."],
      ["leche","milk","🥛","The milk is cold.","La leche está fría."],
      ["pan","bread","🍞","I eat bread for breakfast.","Como pan en el desayuno."],
      ["queso","cheese","🧀","The cheese is yellow.","El queso es amarillo."],
      ["huevo","egg","🥚","I want one egg.","Quiero un huevo."],
      ["arroz","rice","🍚","We eat rice with chicken.","Comemos arroz con pollo."],
      ["carne","meat","🥩","The meat is on the plate.","La carne está en el plato."],
      ["atún","tuna","🍣","I eat tuna with rice.","Como atún con arroz."],
      ["manzana","apple","🍎","The apple is red.","La manzana es roja."],
      ["plátano","banana","🍌","The banana is yellow.","El plátano es amarillo."],
      ["naranja","orange","🍊","This orange is sweet.","Esta naranja es dulce."],
      ["uva","grape","🍇","I want some grapes.","Quiero unas uvas."],
      ["fresa","strawberry","🍓","The strawberry is small.","La fresa es pequeña."],
      ["sandía","watermelon","🍉","The watermelon is very big.","La sandía es muy grande."],
      ["tomate","tomato","🍅","I put tomato in the salad.","Pongo tomate en la ensalada."],
      ["papa","potato","🥔","The potato is from Peru.","La papa es del Perú."],
      ["zanahoria","carrot","🥕","The carrot is orange.","La zanahoria es anaranjada."],
      ["lechuga","lettuce","🥬","The lettuce is fresh.","La lechuga está fresca."],
      ["cebolla","onion","🧅","The onion makes me cry.","La cebolla me hace llorar."],
      ["sopa","soup","🍲","The soup is hot.","La sopa está caliente."],
      ["ensalada","salad","🥗","I eat a salad at lunch.","Como una ensalada en el almuerzo."],
      ["pastel","cake","🍰","The cake is for my birthday.","El pastel es para mi cumpleaños."],
      ["galleta","cookie","🍪","I want one cookie.","Quiero una galleta."],
      ["helado","ice cream","🍦","The ice cream is chocolate.","El helado es de chocolate."],
      ["jugo","juice","🧃","I drink orange juice.","Tomo jugo de naranja."]
    ]
  },
  {
    id: "verbos", nombre: "Acciones (verbos)", emoji: "🏃", color: "#34d399",
    palabras: [
      ["comer","to eat","🍽️","I eat at twelve o'clock.","Yo como a las doce."],
      ["beber","to drink","🥤","She drinks water.","Ella bebe agua."],
      ["dormir","to sleep","😴","I sleep eight hours.","Duermo ocho horas."],
      ["correr","to run","🏃","We run in the park.","Corremos en el parque."],
      ["caminar","to walk","🚶","I walk to school.","Camino a la escuela."],
      ["saltar","to jump","🤸","The children jump.","Los niños saltan."],
      ["hablar","to speak","🗣️","I speak Spanish.","Yo hablo español."],
      ["escuchar","to listen","👂","Listen to the teacher.","Escucha a la maestra."],
      ["leer","to read","📕","I read every night.","Leo todas las noches."],
      ["escribir","to write","✍️","Write your name here.","Escribe tu nombre aquí."],
      ["jugar","to play","🎮","We play together.","Jugamos juntos."],
      ["cantar","to sing","🎤","She sings very well.","Ella canta muy bien."],
      ["bailar","to dance","💃","They dance at the party.","Ellos bailan en la fiesta."],
      ["estudiar","to study","📚","I study English.","Yo estudio inglés."],
      ["aprender","to learn","🧠","I want to learn more.","Quiero aprender más."],
      ["enseñar","to teach","🧑‍🏫","She teaches math.","Ella enseña matemática."],
      ["mirar","to watch","👀","We watch a movie.","Miramos una película."],
      ["abrir","to open","🚪","Open the window, please.","Abre la ventana, por favor."],
      ["cerrar","to close","🔒","Close the door.","Cierra la puerta."],
      ["comprar","to buy","🛒","I buy bread.","Compro pan."],
      ["ayudar","to help","🤝","Can you help me?","¿Puedes ayudarme?"],
      ["trabajar","to work","💼","My father works a lot.","Mi padre trabaja mucho."],
      ["vivir","to live","🏠","I live in Lima.","Vivo en Lima."],
      ["querer","to want","🌟","I want a new book.","Quiero un libro nuevo."],
      ["ir","to go","➡️","I go to the park.","Voy al parque."]
    ]
  },
  {
    id: "colores", nombre: "Colores y números", emoji: "🎨", color: "#facc15",
    palabras: [
      ["rojo","red","🔴","My shirt is red.","Mi camisa es roja."],
      ["azul","blue","🔵","The sky is blue.","El cielo es azul."],
      ["amarillo","yellow","🟡","The sun is yellow.","El sol es amarillo."],
      ["verde","green","🟢","The grass is green.","El pasto es verde."],
      ["negro","black","⚫","My shoes are black.","Mis zapatos son negros."],
      ["blanco","white","⚪","The paper is white.","El papel es blanco."],
      ["morado","purple","🟣","I like the purple one.","Me gusta el morado."],
      ["rosado","pink","🌸","Her dress is pink.","Su vestido es rosado."],
      ["celeste","light blue","🟦","Her eyes are light blue.","Sus ojos son celestes."],
      ["marrón","brown","🟤","The bear is brown.","El oso es marrón."],
      ["gris","gray","🩶","The cat is gray.","El gato es gris."],
      ["uno","one","1️⃣","I have one apple.","Tengo una manzana."],
      ["dos","two","2️⃣","I have two brothers.","Tengo dos hermanos."],
      ["tres","three","3️⃣","There are three books.","Hay tres libros."],
      ["cuatro","four","4️⃣","The table has four legs.","La mesa tiene cuatro patas."],
      ["cinco","five","5️⃣","My hand has five fingers.","Mi mano tiene cinco dedos."],
      ["seis","six","6️⃣","I am in sixth grade.","Estoy en sexto grado."],
      ["siete","seven","7️⃣","A week has seven days.","Una semana tiene siete días."],
      ["ocho","eight","8️⃣","Class starts at eight.","La clase empieza a las ocho."],
      ["nueve","nine","9️⃣","She is nine years old.","Ella tiene nueve años."],
      ["diez","ten","🔟","I count to ten.","Cuento hasta diez."],
      ["veinte","twenty","🔢","There are twenty students.","Hay veinte alumnos."],
      ["cien","one hundred","💯","I got one hundred points.","Saqué cien puntos."],
      ["primero","first","🥇","She is the first one.","Ella es la primera."],
      ["segundo","second","🥈","He is in second place.","Él está en segundo lugar."]
    ]
  },
  {
    id: "casa", nombre: "La casa y la ciudad", emoji: "🏠", color: "#60a5fa",
    palabras: [
      ["casa","house","🏠","My house is small.","Mi casa es pequeña."],
      ["puerta","door","🚪","The door is open.","La puerta está abierta."],
      ["ventana","window","🪟","The window is clean.","La ventana está limpia."],
      ["cocina","kitchen","🍳","My mother is in the kitchen.","Mi madre está en la cocina."],
      ["baño","bathroom","🚿","The bathroom is upstairs.","El baño está arriba."],
      ["cama","bed","🛏️","My bed is comfortable.","Mi cama es cómoda."],
      ["cuarto","bedroom","🛌","My bedroom is blue.","Mi cuarto es azul."],
      ["sala","living room","🛋️","We watch TV in the living room.","Vemos tele en la sala."],
      ["jardín","garden","🌳","There are flowers in the garden.","Hay flores en el jardín."],
      ["techo","roof","🏚️","The roof is red.","El techo es rojo."],
      ["piso","floor","🧱","The floor is cold.","El piso está frío."],
      ["llave","key","🔑","I lost my key.","Perdí mi llave."],
      ["luz","light","💡","Turn on the light.","Prende la luz."],
      ["espejo","mirror","🪞","I look in the mirror.","Me miro en el espejo."],
      ["refrigeradora","refrigerator","❄️","The milk is in the refrigerator.","La leche está en la refrigeradora."],
      ["televisor","television","📺","The television is new.","El televisor es nuevo."],
      ["teléfono","phone","📱","My phone has no battery.","Mi teléfono no tiene batería."],
      ["computadora","computer","💻","I use the computer for homework.","Uso la computadora para la tarea."],
      ["ciudad","city","🏙️","Lima is a big city.","Lima es una ciudad grande."],
      ["calle","street","🛣️","The street is long.","La calle es larga."],
      ["parque","park","🎠","We play in the park.","Jugamos en el parque."],
      ["tienda","store","🏪","The store is closed.","La tienda está cerrada."],
      ["mercado","market","🧺","My mother buys fruit at the market.","Mi madre compra fruta en el mercado."],
      ["hospital","hospital","🏥","The hospital is near.","El hospital está cerca."],
      ["iglesia","church","⛪","The church is very old.","La iglesia es muy antigua."]
    ]
  },
  {
    id: "cuerpo", nombre: "Cuerpo y ropa", emoji: "👕", color: "#f87171",
    palabras: [
      ["cabeza","head","🙂","My head hurts.","Me duele la cabeza."],
      ["cabello","hair","💇","Her hair is long.","Su cabello es largo."],
      ["ojo","eye","👁️","My eyes are brown.","Mis ojos son marrones."],
      ["nariz","nose","👃","The clown has a big nose.","El payaso tiene una nariz grande."],
      ["boca","mouth","👄","Open your mouth.","Abre la boca."],
      ["oreja","ear","👂","The rabbit has long ears.","El conejo tiene orejas largas."],
      ["diente","tooth","🦷","I brush my teeth.","Me lavo los dientes."],
      ["mano","hand","✋","Wash your hands.","Lávate las manos."],
      ["brazo","arm","💪","My arm is strong.","Mi brazo es fuerte."],
      ["pierna","leg","🦵","My leg hurts.","Me duele la pierna."],
      ["pie","foot","🦶","My foot is small.","Mi pie es pequeño."],
      ["dedo","finger","👆","I have ten fingers.","Tengo diez dedos."],
      ["corazón","heart","❤️","My heart beats fast.","Mi corazón late rápido."],
      ["cara","face","😀","Wash your face.","Lávate la cara."],
      ["camisa","shirt","👕","My shirt is white.","Mi camisa es blanca."],
      ["pantalón","pants","👖","These pants are new.","Este pantalón es nuevo."],
      ["vestido","dress","👗","Her dress is beautiful.","Su vestido es hermoso."],
      ["falda","skirt","👚","The skirt is blue.","La falda es azul."],
      ["zapato","shoe","👟","My shoes are dirty.","Mis zapatos están sucios."],
      ["media","sock","🧦","I need clean socks.","Necesito medias limpias."],
      ["sombrero","hat","🎩","He wears a hat.","Él usa un sombrero."],
      ["chompa","sweater","🧥","Put on your sweater.","Ponte tu chompa."],
      ["guante","glove","🧤","The gloves are warm.","Los guantes son abrigadores."],
      ["gorra","cap","🧢","My cap is red.","Mi gorra es roja."],
      ["lentes","glasses","👓","I wear glasses to read.","Uso lentes para leer."]
    ]
  }
];

/* CAZADOR DE ERRORES — traducciones automáticas mal hechas.
   Cada reto: frase en español, traducción MALA, opciones, respuesta correcta y explicación. */
const ERRORES = [
  { es:"Estoy de acuerdo contigo.", mala:"I am of agreement with you.",
    opciones:["I agree with you.","I am of agreement with you.","I am agree with you."], correcta:0,
    porque:"El traductor tradujo palabra por palabra. En inglés no se dice «I am of agreement», se usa el verbo <b>agree</b>." },
  { es:"Tengo hambre.", mala:"I have hunger.",
    opciones:["I have hunger.","I am hungry.","I has hungry."], correcta:1,
    porque:"En español usamos «tener» hambre, pero en inglés se usa <b>to be</b>: I <b>am</b> hungry." },
  { es:"Tengo 12 años.", mala:"I have 12 years.",
    opciones:["I have 12 years.","I am 12 years old.","I have 12 years old."], correcta:1,
    porque:"La edad en inglés va con <b>to be</b>: I <b>am</b> 12 years <b>old</b>." },
  { es:"¿Cómo te llamas?", mala:"How do you call yourself?",
    opciones:["What is your name?","How do you call yourself?","How you call?"], correcta:0,
    porque:"Es una expresión fija. La traducción literal suena rarísima; lo natural es <b>What is your name?</b>" },
  { es:"Hace frío.", mala:"It makes cold.",
    opciones:["It makes cold.","It is cold.","He makes cold."], correcta:1,
    porque:"«Hacer» aquí no es <i>make</i>. Para el clima se usa <b>It is + adjetivo</b>." },
  { es:"Me gusta el chocolate.", mala:"Me likes the chocolate.",
    opciones:["Me likes the chocolate.","I like chocolate.","I likes chocolate."], correcta:1,
    porque:"El sujeto es <b>I</b>, no «me». Y en inglés no lleva artículo: <i>chocolate</i>, no <i>the chocolate</i>." },
  { es:"Tengo que estudiar.", mala:"I have that study.",
    opciones:["I have to study.","I have that study.","I must to study."], correcta:0,
    porque:"El traductor convirtió «que» en <i>that</i>. La forma correcta es <b>have to</b> + verbo." },
  { es:"Mi madre está en la cocina.", mala:"My mother is in the cook.",
    opciones:["My mother is in the cook.","My mother is in the kitchen.","My mother is in the cooker."], correcta:1,
    porque:"«Cocina» tiene dos sentidos: el cuarto (<b>kitchen</b>) y cocinar (<i>cook</i>). El traductor eligió el equivocado." },
  { es:"El banco está cerrado.", mala:"The bench is closed.",
    opciones:["The bench is closed.","The bank is closed.","The banking is closed."], correcta:1,
    porque:"«Banco» puede ser asiento (<i>bench</i>) o entidad (<b>bank</b>). Sin contexto, el traductor se equivoca." },
  { es:"Voy a tomar un taxi.", mala:"I go to drink a taxi.",
    opciones:["I go to drink a taxi.","I am going to take a taxi.","I am going to drink a taxi."], correcta:1,
    porque:"«Tomar» no siempre es <i>drink</i>. Con transporte es <b>take</b>." },
  { es:"Está lloviendo.", mala:"Is raining.",
    opciones:["Is raining.","It is raining.","He is raining."], correcta:1,
    porque:"En español el sujeto puede desaparecer, en inglés <b>no</b>. Siempre va <b>It</b>." },
  { es:"Tengo sed.", mala:"I have thirst.",
    opciones:["I am thirsty.","I have thirst.","I have thirsty."], correcta:0,
    porque:"Igual que con hambre: en inglés es <b>I am thirsty</b>." },
  { es:"Ella tiene el pelo largo.", mala:"She has the hair long.",
    opciones:["She has the hair long.","She has long hair.","She has hair long."], correcta:1,
    porque:"En inglés el adjetivo va <b>antes</b> del sustantivo: <i>long hair</i>, no <i>hair long</i>." },
  { es:"Estoy aburrida.", mala:"I am boring.",
    opciones:["I am boring.","I am bored.","I am bore."], correcta:1,
    porque:"<b>Bored</b> = yo me aburro. <i>Boring</i> = yo aburro a los demás. ¡Cuidado con ese error!" },
  { es:"Realmente, yo actualmente estudio inglés.", mala:"Actually, I actually study English.",
    opciones:["Actually, I actually study English.","Actually, I currently study English.","Really, I currently study English."], correcta:2,
    porque:"<i>Actually</i> NO significa «actualmente», significa «en realidad». Actualmente es <b>currently</b>. Son falsos amigos." },
  { es:"Mi carpeta está sucia.", mala:"My folder is dirty.",
    opciones:["My folder is dirty.","My desk is dirty.","My carpet is dirty."], correcta:1,
    porque:"En Perú «carpeta» es el mueble del aula: <b>desk</b>. El traductor pensó en una carpeta de papeles." },
  { es:"Buenos días, señora.", mala:"Good days, lady.",
    opciones:["Good days, lady.","Good morning, ma'am.","Good day, madam lady."], correcta:1,
    porque:"El saludo es fijo y en singular: <b>Good morning</b>. No se traduce palabra por palabra." },
  { es:"Hace dos años que vivo aquí.", mala:"It makes two years that I live here.",
    opciones:["It makes two years that I live here.","I have lived here for two years.","I live here since two years."], correcta:1,
    porque:"El inglés usa <b>have lived ... for</b>. La traducción literal no existe en inglés." },
  { es:"Por favor, apaga la luz.", mala:"For favor, off the light.",
    opciones:["For favor, off the light.","Please, turn off the light.","Please, apagate the light."], correcta:1,
    porque:"«Por favor» es <b>please</b> y «apagar» es el verbo compuesto <b>turn off</b>." },
  { es:"Nos vemos mañana.", mala:"We see us tomorrow.",
    opciones:["We see us tomorrow.","See you tomorrow.","We look tomorrow."], correcta:1,
    porque:"Es una despedida hecha: <b>See you tomorrow</b>. Traducirla literalmente da una frase sin sentido." }
];
